name: CI
on: [push, pull_request]

jobs:
  build-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: docker_img:latest
          outputs: type=docker,dest=/tmp/docker_img.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker_img
          path: /tmp/docker_img.tar

      
  build-latex:
    runs-on: ubuntu-latest
    needs: build-dockerfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docker_img
          path: /tmp

      - name: Load Docker and run image
        run: |
          docker load --input /tmp/docker_img.tar
          docker run docker_img:latest bash -c 'echo "$PWD"; ls; echo -e "\n\n\n"; find . -name "main\.tex"'

  # Temporarily keeping this for comparison
  old-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Dockerfile
        run: |
          docker build -t docker_img:latest -f ./Dockerfile .
          docker run docker_img:latest bash -c 'echo "$PWD"; ls; echo -e "\n\n\n"; find . -name "main\.tex"'

