name: CI
on: [push, pull_request]

jobs:
  build-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.devcontainer/Dockerfile
          tags: docker_img:latest
          outputs: type=docker,dest=/tmp/docker_img.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker_img
          path: /tmp/docker_img.tar

      
  build-latex:
    runs-on: ubuntu-latest
    needs: build-dockerfile
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docker_img
          path: /tmp

      - name: Load Docker and run image
        run: |
          docker load --input /tmp/docker_img.tar
          docker run --rm docker_img:latest make

  # Temporarily keeping this for comparison
  old-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Dockerfile
        run: |
          docker build -t $GITHUB_REPOSITORY -f ./.devcontainer/Dockerfile .
          docker run --rm -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE -w $GITHUB_WORKSPACE --user latex $GITHUB_REPOSITORY  make
