name: CI
on: [push, pull_request]

jobs:
  # Temporarily keeping this for comparison
  latex-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Dockerfile
        run: |
          docker build -t docker_img:latest -f ./.devcontainer/Dockerfile .
          docker run -v $GITHUB_WORKSPACE:/workspace -w /workspace docker_img:latest make

  latex-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build latex
        uses: aalbaali/latex-action@master
        with:
          root_file: |
            src/main.tex
          work_in_root_file_dir: true

          # Args:
          #   -cd                 :   Change directory to the root file (this way it can find the cc.tex file)
          #   -pdf                :   Generate a PDF using pdflatex
          #   --output-directory  :   Build directory, with respect to the calling command
          # For more info, refer to
          #   https://manpages.ubuntu.com/manpages/bionic/man1/latexmk.1L.html
          args: -cd -pdf --output-directory=../build
